blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    #       example : /
    url(r'^$', PostLV.as_view(), name='index'),

    #       example : /7/
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='post_detail'),

    #       example : /add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),

    #       example : /change/
    url(r'^change/$', PostChangeLV.as_view(), name='change'),

    #       example : /7/update/
    url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),

    #       example : /7/delete/
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='delete'),

]

chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.create, name='new_room'),
    url(r'^roomlist/$', views.showroomList, name='list'),
    url(r'^enter/$', views.enter, name='enter'),

]

friend/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    #       ID로 친구(user)를 검색한다.
    url(r'^search/', views.search, name='search'),

    #       나의 친구 목록을 보여준다.
    url(r'^list/$', views.myList, name='list'),

    #       선택된 친구 한 명을 내 친구로 추가한다.
    url(r'^add/$', views.add, name='add')
]

multichat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #       root url '/'에 대한 처리.
    url(r'^$', HomeView.as_view(), name="home"),

    #       회원가입 앱
    url(r'^accounts/', include('accounts.urls')),

    #       친구추가 앱
    url(r'^friend/', include('friend.urls', namespace='friend')),

    #       본격 채팅 앱
    url(r'^chat/', include('chat.urls', namespace='chat')),

    #       게시판 글 쓰기 앱
    url(r'^blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friend/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class FriendShip(models.Model):
    from_friend=models.ForeignKey(get_user_model(), related_name="friend_set")
    to_friend=models.ForeignKey(get_user_model(), related_name="to_friend_set")

    def __str__(self):
        return "%s, %s" % (self.from_friend.username, self.to_friend.username)


    class Meta:
        unique_together=(("to_friend", "from_friend"), )

friend/forms.py
from django import forms
from accounts.form_validators import phone_validator
from django.core.validators import MinLengthValidator
from accounts.models import Profile

class searchForm(forms.Form):
    phone_number=forms.CharField(validators=[phone_validator], label='휴대전화 번호',
                                 max_length=15, required=False)
    nickname = forms.CharField(max_length=20, label='닉네임',
                               validators=[MinLengthValidator(3)], required=False)


    def clean(self):
        self.cleaned_data=super().clean()
        querySet=Profile.objects.all()
        nickname=self.cleaned_data.get('nickname')
        phone_number=self.cleaned_data.get('phone_number')

        #       예외처리 시작.
        #       case 1) 사용자가 아무런 값을 입력하지 않았음
        if ((nickname == '') and (phone_number == '')):
            raise forms.ValidationError("아무런 값을 입력하지 않으셨습니다. 닉네임 또는 폰번호의 값을 입력해 검색해주세요.")

        if nickname != '':
            querySet=querySet.filter(nickname=nickname)
        if phone_number != '':
            querySet=querySet.filter(phone_number=phone_number)

        #       case 2) 사용자가 값을 입력했으나 DB에 없는 값이면...
        if (querySet.count() == 0):
            raise forms.ValidationError("그러한 사용자는 존재하지 않습니다.\n"
                                        "친구의 닉네임 및 폰번호 값을 다시 한번 확인해주세요.")

friend/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import FriendShip
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.db.utils import IntegrityError
from django.shortcuts import get_object_or_404
from .forms import searchForm
from accounts.models import Profile
from django.contrib import messages


# Create your views here.
@login_required
def search(request):
    context=dict()
    context["friend"]=None

    if request.method == "POST":
        form=searchForm(request.POST)
        if(form.is_valid()):
            nickname=form.cleaned_data['nickname']
            phone_number=form.cleaned_data['phone_number']
            querySet=Profile.objects.all()

            if nickname != '':
                querySet = querySet.filter(nickname=nickname)
            if phone_number != '':
                querySet = querySet.filter(phone_number=phone_number)

            if(querySet[0].user == request.user):
                messages.add_message(request, messages.ERROR, '친구목록에 "나"는 포함될 수 없습니다. 친구를 다시 검색해주세요.')
                return render(request, "friend/friend_search.html",{
                                  'form':searchForm(),
                                  'friend':None
                              })

            context["friend"]=querySet[0]

    else:
        form=searchForm()

    context["form"]=form
    return render(request, "friend/friend_search.html", context)


@login_required
def myList(request):
    U=get_object_or_404(get_user_model(), username=request.user.username)
    List=[friendship.to_friend for friendship in U.friend_set.all()]

    context=dict()
    context["List"]=List
    return render(request, "friend/friend_list.html", context)


@login_required
def add(request):
    try:
        U1=request.user
        ref = get_object_or_404(Profile, nickname=request.POST["choice"])
        U2=ref.user
    except(Exception):
        return render(request, "friend/friend_search.html", {
            "comment" : "친구 ID를 입력해주세요."
        })
    else:
        try:
            FriendShip.objects.create(from_friend=U1, to_friend=U2)
            FriendShip.objects.create(from_friend=U2, to_friend=U1)
            return HttpResponseRedirect(reverse_lazy('friend:search'))
        except(IntegrityError):
            return render(request, "friend/friend_search.html",
                          {
                "error_msg" : "당신은 이미 이 사람과 친구입니다.",
                "form" : searchForm()
            })

friend/templates/friend/friend_list.html
{% extends "base.html" %}
{% block title %}친구목록{% endblock %}


{% block extra_body %}
{% if List %}

    <div class="container">
        <h3>나의 친구들(닉네임 list).</h3>
        <hr/>
        <form action="{% url 'chat:new_room' %}" method="post" class = "bs-example bs-example-form" role = "form">
            {% csrf_token %}
            <div class="col-sm-12">

                {% for frn in List %}
                <div class="checkbox">
                    <label style="font-size: 1.5em">
                        <input type="checkbox" name="chk_info[]" value="{{ frn.username }}" />

                        {{ frn.profile.nickname }}
                    </label>
                </div>
                {% endfor %}

            </div>

            <div class="col-xs-12" style="height:20px;"></div>

            <h4>채팅방 제목을 정해주세요. 입력하지 않으셔도 무방합니다. default 값은 채팅 참여자들의 닉네임으로 이루어집니다.</h4>

            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-star"></span></span>
                <input type="text" class="form-control" placeholder="채팅방 이름" name="roomTitle">
            </div>

            <div class="col-xs-12" style="height:40px;"></div>

            <input type="submit" class="btn btn-primary" value="채팅방만들기."/>
        </form>
    </div>

{% elif List|length == 0 %}
    <div class="container"><h1><strong> 내 친구가 없습니다. 친구를 추가해주세요.</strong></h1></div>
{% endif %}

{% endblock extra_body %}

friend/templates/friend/friend_search.html
{% extends "base.html" %}
{% block title %}친구검색{% endblock %}

{% load bootstrap3 %}

{% block extra_body %}
    {% bootstrap_javascript jquery=1 %}
    {% bootstrap_messages %}

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>유저 검색 기능을 제공합니다.</h3>
                <hr/>
                {% if error_msg %}
                    <div class="alert alert-warning">
                        <strong>Oops!</strong> {{ error_msg }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container">
        <form action="" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="검색" class="btn btn-primary btn-lg"/>
        </form>
    </div>

    <div class="col-xs-12" style="height : 70px;"></div>

    {% if friend %}
        <div class="container">
            <form action="{% url 'friend:add' %}" method="post">
                {% csrf_token %}

                <input type="checkbox" id="USER" name="choice" value="{{ friend.nickname }}"/>
                <label for="USER">Friend : {{ friend.nickname }}, {{ friend.phone_number }}</label>
                <br/>

                <input type="submit" value="추가하겠습니다." class="btn btn-primary"/>
            </form>
        </div>
    {% endif %}
{% endblock extra_body %}


{% load staticfiles %}
{% block extraJS %}{% static 'friend/search.js' %}{% endblock extraJS %}