blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    #       example : /
    url(r'^$', PostLV.as_view(), name='index'),

    #       example : /7/
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='post_detail'),

    #       example : /add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),

    #       example : /change/
    url(r'^change/$', PostChangeLV.as_view(), name='change'),

    #       example : /7/update/
    url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),

    #       example : /7/delete/
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='delete'),

]

chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.create, name='new_room'),
    url(r'^roomlist/$', views.showroomList, name='list'),
    url(r'^enter/$', views.enter, name='enter'),

]

multichat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #       root url '/'에 대한 처리.
    url(r'^$', HomeView.as_view(), name="home"),

    #       회원가입 앱
    url(r'^accounts/', include('accounts.urls')),

    #       친구추가 앱
    url(r'^friend/', include('friend.urls', namespace='friend')),

    #       본격 채팅 앱
    url(r'^chat/', include('chat.urls', namespace='chat')),

    #       게시판 글 쓰기 앱
    url(r'^blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from .choices import POSTTYPE_CHOICES, BLOODTYPE_CHOICES
# Create your models here.

class Post(models.Model):
    author=models.ForeignKey(settings.AUTH_USER_MODEL)
    title=models.CharField(verbose_name='TITLE', max_length=50)
    post_type=models.CharField(max_length=1, choices=POSTTYPE_CHOICES)
    blood_type=models.IntegerField(blank=True, choices=BLOODTYPE_CHOICES)
    content=models.TextField(verbose_name='본문')
    create_date=models.DateTimeField(verbose_name='생성날짜', auto_now_add=True)
    modify_date=models.DateTimeField(verbose_name='수정날짜', auto_now=True)


    class Meta:
        verbose_name='post'
        verbose_name_plural='posts'
        ordering=('-modify_date', )


    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.id, ))


    def get_previous_post(self):
        return self.get_previous_by_modify_date()


    def get_next_post(self):
        return self.get_next_by_modify_date()

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from multichat.views import LoginRequiredMixin


# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 5


class PostDV(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'post_type', 'blood_type', 'content', ]
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.author=self.request.user
        return super().form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'post_type', 'blood_type', 'content', ]
    success_url = reverse_lazy('blog:index')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% block extra_body %}
    <div id="board" class="container">
        <table class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Title</th>
                    <th>작성자 nickname</th>
                    <th>작성시각</th>
                    <th>게시글 타입</th>
                    <th>혈액형</th>
                </tr>
            </thead>
            <tbody>
                {% for post in object_list %}
                    <tr>
                        <td>{{ post.id }}</td>
                        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </td>
                        <td>{{ post.author.profile.nickname }}</td>
                        <td>{{ post.modify_date | date:"Y-m-d D" }}</td>
                        <td>{{ post.get_post_type_display }}</td>
                        <td>{{ post.get_blood_type_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <br/>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <a href="{% url 'blog:add' %}" class="btn btn-primary pull-right">글쓰기</a>
                <a href="{% url 'blog:change' %}" class="btn btn-primary pull-right">내 글 목록</a>
            </div>
        </div>
    </div>

    <br/>

    <div class="text-center pagination-wrap">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a> </li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }}<span class="sr-only">(current)</span> </span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a> </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a> </li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    </div>
{% endblock extra_body %}

blog/templates/blog/post_change_list.html
{% extends 'base.html' %}

{% block extra_body %}
    <div id="board" class="container">
        <div class="row">
        <table class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>수정시각</th>
                    <th>게시글 타입</th>
                    <th>수정</th>
                    <th>삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for post in object_list %}
                    <tr>
                        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </td>
                        <td>{{ post.create_date | date:"Y-m-d D" }}</td>
                        <td>{{ post.get_post_type_display }}</td>
                        <td><a href="{% url 'blog:update' post.pk %}">수정하기</a> </td>
                        <td><a href="{% url 'blog:delete' post.pk %}">삭제하기</a> </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock extra_body %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    글 삭제
{% endblock %}

{% block extra_body %}
    <div class="container">
        <h2>글 제목 : {{ object }}</h2>
        <h4>해당 글을 정말 삭제 하시겠습니까?</h4>

        <hr/>

        <form action="" method="post">
            {% csrf_token %}
                <a href="{{ object.get_absolute_url }}" class="btn btn-info" role="button">아니요. 취소!</a>
                <input type="submit" value="예, 삭제하겠습니다." class="btn btn-danger"/>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block extra_body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ object.title }}</h2>

                {{ object.content|linebreaks }}

                <hr/>


                <a href="{% url 'blog:index' %}" class="btn btn-primary">전체 글 목록</a>
                <a href="{% url 'blog:change' %}" class="btn btn-primary">내 글 목록</a>
                <a href="{% url 'blog:update' object.pk %}" class="btn btn-primary">수정하기</a>
                <a href="{% url 'blog:delete' object.pk %}" class="btn btn-primary">삭제하기</a>
            </div>
        </div>
    </div>
{% endblock extra_body %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% block title %}
    새 글 작성
{% endblock %}

{% block extra_body %}
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	<form method="POST" class="login-form col-md-12" action=".">
		{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="저장" class="btn btn-success"/>
        <br/>
        <a href="{% url 'blog:index' %}">
            <button type="button" class="btn btn-danger">취소</button>
        </a>
	</form>
</div>
{% endblock %}