blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    #       example : /
    url(r'^$', PostLV.as_view(), name='index'),

    #       example : /7/
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='post_detail'),

    #       example : /add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),

    #       example : /change/
    url(r'^change/$', PostChangeLV.as_view(), name='change'),

    #       example : /7/update/
    url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),

    #       example : /7/delete/
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='delete'),

]

chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.create, name='new_room'),
    url(r'^roomlist/$', views.showroomList, name='list'),
    url(r'^enter/$', views.enter, name='enter'),

]

multichat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #       root url '/'에 대한 처리.
    url(r'^$', HomeView.as_view(), name="home"),

    #       회원가입 앱
    url(r'^accounts/', include('accounts.urls')),

    #       친구추가 앱
    url(r'^friend/', include('friend.urls', namespace='friend')),

    #       본격 채팅 앱
    url(r'^chat/', include('chat.urls', namespace='chat')),

    #       게시판 글 쓰기 앱
    url(r'^blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="My first web project">
    <meta name="author" content="juhyun-park">
    <title>{% block title %}Carousel Template for Bootstrap{% endblock title %}</title>

    {% load staticfiles %}
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" />

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet" />

    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap-theme.css' %}" />

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'ie10-viewport-bug-workaround.css' %}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock extrastyle %}" type="text/css" />

    <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% block extraJS %}{% endblock extraJS %}"></script>

    {% block extra_head %}{% endblock extra_head %}
</head>

<body>
    <div class="container">
        <div class="row">
            <!-- Navigation -->
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
                    </div>


                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{% url 'blog:index' %}">전체 글 목록</a></li>
                            <li><a href="{% url 'friend:search' %}">친구검색 및 추가</a></li>
                            <li><a href="{% url 'friend:list' %}">친구목록 및 채팅방만들기</a></li>
                            <li><a href="{% url 'chat:enter' %}">채팅하기</a></li>

                            <!--    아래의 템플릿 변수 Seoul은 blog.context_processor.py에
                            정의되어 있는 dict 자료구조의 key이다.   -->
                            <!--    view에서 render함수 호출할 때 context 객체를 인자로 넘겨주지 않아도
                            context_processor 덕분에 템플릿 변수를 사용할 수 있다. -->
                            <!--    <li><a href="#">Contact {# {{ Seoul }} #}</a></li>    -->
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            {% if not user.is_authenticated %}
                                <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                                <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            {% else %}
                                <li><a href="{% url 'profile' %}"><span class="glyphicon glyphicon-cog"></span> My Profile</a> </li>
                                <li><a href="{% url 'logout' %}?next={{ request.path }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a> </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Navigation end -->


            {% block chatting %}{% endblock chatting %}
            {% block extra_body %}{% endblock extra_body %}


            <!-- Bootstrap core JavaScript -->
            <!-- Placed at the end of the document so the pages load faster -->

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script>window.jQuery || document.write('<script src="static/js/jquery-3.2.1.min.js"><\/script>')</script>
            <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
            <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
            <script src="{% static 'ie10-viewport-bug-workaround.js' %}"></script>


            <footer>
                <p class="pull-right"><a href="#">Back to top</a></p>
                <p>&copy; 박주현 2017. 여름. </p>
            </footer>
        </div>
    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Chat app powered by python 3.
{% endblock %}


{% block extra_body %}
    <!-- Carousel -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img class="first-slide" src="/media/nanumi/nanumi1.png" alt="First slide" />
                <div class="container">
                    <div class="carousel-caption">
                        <!-- caption 사용 방법
                        <h1>Example headline.</h1>
                        <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                        -->
                    </div>
                </div>
            </div>

            <div class="item">
                <img class="second-slide" src="/media/nanumi/nanumi2.jpg" alt="Second slide" />
                <div class="container">
                    <div class="carousel-caption">
                        <!-- caption 사용 방법
                        <h1>Another example headline.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                        -->
                    </div>
                </div>
            </div>

            <div class="item">
                <img class="third-slide" src="/media/nanumi/nanumi3-3.jpg" alt="Third slide" />
                <div class="container">
                    <div class="carousel-caption">
                        <!-- caption 사용 방법
                        <h1>One more for good measure.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                        -->
                    </div>
                </div>
            </div>
        </div>

        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!-- end Carousel -->

    <div class="container"><div class="row"><p></p><p></p></div> </div>

    <!-- Marketing messaging and featurettes -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
        <!--

        <div class="row">
            <div class="col-lg-3">
                <img class="img-circle" src="/media/default-picture.jpg" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>

            <div class="col-lg-3">
                <img class="img-circle" src="/media/default-picture.jpg" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>

            <div class="col-lg-3">
                <img class="img-circle" src="/media/default-picture.jpg" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>

            <div class="col-lg-3">
                <img class="img-circle" src="/media/default-picture.jpg" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
        -->


        <!-- START THE FEATURETTES -->
        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">간단한 사이트 소개. <span class="text-muted">Let me introduce my site.</span></h2>
                <p class="lead">목적 : 수혈 환자들을 위한 커뮤니티 형성.</p>

                <p class="lead">
                    - 상단 네비게이션바에 있는 각종 메뉴들에 대한 설명입니다.
                    <hr/>
                    <dl class="dl-horizontal">
                        <dt><h3>전체 글 목록</h3></dt>
                        <dd><h4>게시판에는 세 종류의 게시글이 있습니다.(자유게시판, Need help, Support You). <br/>
                            게시글 작성자의 닉네임을 확인해서 수혈이 필요한 환자 또는 헌혈을 해줄 수 있는 고마운 분이 누구인지 확인해주세요.</h4></dd>

                        <dt><h3>친구검색 및<br/> 추가</h3></dt>
                        <dd><h4>채팅기능을 사용하기 위해선 먼저 그 사람과 내가 친구관계에 있어야해요. <br/>
                            게시판에서 확인한 익명의 사람을 닉네임으로 검색해주세요.<br/>
                            또는 실제 나의 지인이 이 사이트에 회원가입되어 있다면 내 지인을 검색할 수 있습니다. <br/>
                            만약 상대방이 나를 친구추가하면 내 친구목록에 자동으로 상대방이 추가됩니다.</h4></dd>

                        <dt><h4>친구목록 및<br/> 채팅방만들기</h4></dt>
                        <dd><h4>나의 친구 목록이 보여집니다. <br/>
                            채팅할 친구를 여럿 선택해서 채팅방을 만들어주세요.</h4></dd>

                        <dt><h3>채팅하기</h3></dt>
                        <dd><h4>이제 채팅하실 수 있습니다. <br/>
                            채팅방 title을 클릭하면 해당 채팅방에 입장됩니다.<br/>
                            title을 다시 클릭하면 채팅방이 닫힙니다.</h4></dd>
                    </dl>
                </p>
            </div>

            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" src="/media/first1.png" alt="Generic placeholder image">
            </div>
        </div>

        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7 col-md-push-5">
                <h2 class="featurette-heading">이 사이트는 아직 모든 브라우저를 완벽하게 지원하지 못합니다.. <span class="text-muted">Our website has some constraints.</span></h2>
                <p class="lead">안드로이드 스마트폰에 기본으로 내장되어 있는 '인터넷' 앱에서는 채팅기능이 지원되지 않습니다.<br/>
                                데스크톱 브라우저의 경우 크롬, 파이어폭스, 최신버전의 인터넷 익스플로러로 접속해주세요.
                </p>
            </div>

            <div class="col-md-5 col-md-pull-7">
                <img class="featurette-image img-responsive center-block" src="/media/second2.jpg" alt="Generic placeholder image">
            </div>
        </div>

        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">그리고 앞으로 추가할 기능들... <span class="text-muted">The following features will be applied soon.</span></h2>

                <p class="lead">게시판 글(post)에 댓글달기.</p>
                <p class="lead">게시판 글(post)을 검색하는 기능.</p>
            </div>

            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" src="/media/fourth4.jpg" alt="Generic placeholder image">
            </div>
        </div>

        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-7 col-md-push-5">
                <h2 class="featurette-heading">사이트 둘러보기. <span class="text-muted">Beta test.</span></h2>

                <p class="lead">손님계정으로 로그인하여 사이트를 둘러보세요.<br/>
                    모든 기능을 사용할 수 있어요. 게시글도 작성가능하고, 채팅방 입장도 가능해요. 물론 친구검색, 추가, 채팅방 만들기도 가능합니다.
                </p>
                <p class="lead">아이디 : guest1 // 패스워드 : betatest2017<br/>
                    아이디 : guest2 // 패스워드 : betatest2017<br/>
                    아이디 : guest3 // 패스워드 : betatest2017
                </p>
            </div>

            <div class="col-md-5 col-md-pull-7">
                <img class="featurette-image img-responsive center-block" src="/media/third3.jpg" alt="Generic placeholder image">
            </div>
        </div>


        <hr class="featurette-divider">
        <!-- /END THE FEATURETTES -->

    </div>
    <!-- /.container -->
{% endblock extra_body %}

templates/index.html
{% extends "base.html" %}

{% block title %}MultiChat Example{% endblock %}
{% block header_text %}MultiChat Example{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "chat/chat.css" %}{% endblock extrastyle %}


{% block content %}

    <ul class="rooms">
        {% for room in rooms %}
            <li class="room-link" data-room-id="{{ room.id }}">{{ room }}</li>
        {% empty %}
            <p class="empty">No chat rooms defined. Maybe make some in the <a href="{% url 'admin:index' %}">admin</a>?</p>
        {% endfor %}
    </ul>

    <div id="chats">
    </div>

{% endblock %}


{% block extra_body %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_path = ("/chat/stream/");
            console.log("Connecting to " + ws_path);

            var webSocketBridge = new channels.WebSocketBridge();
            webSocketBridge.connect(ws_path);
            // Handle incoming messages
            webSocketBridge.listen(function(data) {
                // Decode the JSON
                console.log("Got websocket message", data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                                "<h2>" + data.title + "</h2>" +
                                "<div class='messages'></div>" +
                                "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        webSocketBridge.send({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        });
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // display previous msgs.
                    var array=JSON.parse(data.prev_msg);
                    var output="";
                    for(var i=0; i<array.length; i++){
                        output+=(
                            "<div class='message'>"+
                                "<span class='username'>"+array[i].fields.handle+"</span>"+
                                "<span class='body'>"+array[i].fields.message+"</span>"+
                            "</div>");
                    }       //      array[i].fields.timestamp
                    var start=roomdiv.find(".messages");
                    start.append(output);

                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            });

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("li.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    webSocketBridge.send({
                        "command": "leave",
                        "room": roomId
                    });
                } else {
                    // Join room
                    $(this).addClass("joined");
                    webSocketBridge.send({
                        "command": "join",
                        "room": roomId
                    });
                }
            });

            // Helpful debugging
            webSocketBridge.socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            webSocketBridge.socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
{% endblock %}